---
# The minus in YAML this indicates a list item. the playbook contains a list of plays,
# with each play being a dictionary
-
# Hosts: lists of target hosts that we'll run playbooks on
  hosts: all
  become: true
# Vars: variables that apply to the play on all target systems
# Tasks: list of tasks that will be executed within play, including pre and post tasks

  tasks:
    - name: Ping all hosts
      ping:
# Handlers: list of handlers (notification tasks) that are executed with `notify` keyword from `tasks`
# Roles: list of roles (dedicated tasks ) to be imported into the play
# Note: not all are required to be used in single playbook
# Every YAML file file should end with three dots
...
