---
# The minus in YAML this indicates a list item. the playbook contains a list of plays,
# with each play being a dictionary
-
# Hosts: lists of target hosts that we'll run playbooks on
  hosts: db
  become: true
# Vars: variables that apply to the play on all target systems
  vars:
    motd: "Welcome to DB Server - Deployed by Ansible"
# Tasks: list of tasks that will be executed within play, including pre and post tasks

  tasks:
    - name: Configure a MOTD (Message Of The Day) on DB server
      file:
        path: /etc/motd
        state: absent 
      notify: Remove of MOTD
# Handlers: list of handlers (notification tasks) that are executed with `notify` keyword from `tasks`
  handlers:
  - name: Remove of MOTD
    debug:
      msg: The MOTD was removed
# Roles: list of roles (dedicated tasks ) to be imported into the play
# Note: not all are required to be used in single playbook
# Every YAML file file should end with three dots
...
